case: "case_ID"  # case ID (could be cartridge number or something else)

general_paths:
  path_to_cartridge_folder: "absolute_path_to_the_folder_containing_the_raw_tif_images"
  path_to_results_folder: "absolute_path_to_your_results_folder"


cropped_img_parameter:
  img_size: 48   # cropped image size


